spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/task_management_db
    password: root
    username: root
  flyway:
    url: jdbc:mysql://localhost:3306/task_management_db
    user: root
    password: root
